# Generated by Django 6.0.7 on 2026-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screen_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gpu', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Computer',
                'verbose_name_plural': 'Computers',
                'db_table': 'computers',
            },
        ),
    ]
