# Generated by Django 5.0.14 on 2026-07-13 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='movies/', validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(30), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
