# Generated by Django 5.0.14 on 2026-07-21 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, default='💖', null=True, upload_to='clothes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp', 'jpeg'])]),
        ),
    ]
