# Generated by Django 5.0.14 on 2026-07-21 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp', 'jpeg'])]),
        ),
    ]
