# Generated by Django 6.0.7 on 2026-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('divan', 'Divan'), ('stol', 'Stol'), ('stul', 'Stul'), ('shkaf', 'Shkaf'), ('karavot', 'Karavot'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_have', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mebel',
                'verbose_name_plural': 'Mebellar',
                'ordering': ['-created_at'],
            },
        ),
    ]
