# Generated by Django 6.0.7 on 2026-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('mexanism', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('remenka', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watches',
                'db_table': 'watches',
            },
        ),
    ]
