# Generated by Django 6.0.7 on 2026-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField()),
                ('is_tikonli', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flowers',
                'db_table': 'flowers',
            },
        ),
    ]
